########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

cloud_name: aws

aws_region: eu-central-1

# Terraform
tf_environment:
  AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ vault_aws_secret_key }}"

