########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and eks
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

- name: Delete Boutique Application
  ansible.builtin.import_playbook: application/delete.yaml

- name: Delete eks Cluster Addons
  ansible.builtin.import_playbook: eks_cluster_addons/delete.yaml

- name: Delete eks Cluster
  ansible.builtin.import_playbook: eks_cluster/delete.yaml

# - name: Delete networking stuff
#   ansible.builtin.import_playbook: vpc/delete.yaml
